# Default values for filebrowser.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

meta:
  namespace: default
  name: filebrowser

image:
  repository: filebrowser/filebrowser
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 8080
  targetPort: 80
  # with type = NodePort
  # nodePort: 8080


# volume:
  # hostPathSRV: "/var/lib/filebrowser/srv"
  # hostPathDB: "/var/lib/filebrowser/database.db"