meta:
  namespace: default
  name: nginx

image:
  repository: shalldie/alpineos
  pullPolicy: IfNotPresent
  tag: "alpine3.20-nginx1.26.2"
  command:
    - nginx
    - -g
    - '"daemon off;"'

service:
  type: ClusterIP
  port: 8080
  targetPort: 80
  # with type = NodePort
  # nodePort: 8080
# -
# all *.conf, volume to "/etc/nginx/http.d"
# volume: "/etc/nginx/http.d"
