meta:
  namespace: default
  name: minio

image:
  repository: minio/minio
  pullPolicy: IfNotPresent
  tag: "latest"

env:
  - name: MINIO_ROOT_USER
    value: minio
  - name: MINIO_ROOT_PASSWORD
    value: minio123
  # - name: MINIO_SERVER_URL
  #   value: http://127.0.0.1:9000
  # - name: MINIO_BROWSER_REDIRECT_URL
  #   value: http://127.0.0.1:9001

service:
  port: 9000
  # nodePort: 9000

# 可视化 console
console:
  port: 9001
  # nodePort: 9001
#
# volume:
#   数据
#   data: "/var/lib/minio/data"
#   配置
#   config: "/var/lib/minio/config"
