replicaCount: 1

meta:
  namespace: default
  name: filebrowser

image:
  repository: filebrowser/filebrowser
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 8080
  targetPort: 80
  # with type = NodePort
  # nodePort: 8080

ingress:
  enable: false
  baseURL: "/"

volume: {}
  # static serve
  # hostPathSRV: "/var/lib/filebrowser/srv"
  # config database，需要提前创建 `touch database.db`，否则会被识别成文件夹
  # hostPathDB: "/var/lib/filebrowser/database.db"