{{- if .Values.ingress.enable }}
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  namespace: {{ .Values.meta.namespace }}
  name: {{ .Values.meta.name }}
spec:
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: {{ .Values.ingress.baseURL }}
            backend:
              service:
                name: {{ .Values.meta.name }}
                port:
                  number: {{ .Values.service.port }}
{{ end }}