meta:
  namespace: default
  name: minio

image:
  repository: minio/minio
  pullPolicy: IfNotPresent
  tag: "latest"

user:
  name: minio
  password: minio123

service:
  port: 9000
  # nodePort: 9000

# 可视化 console
console:
  port: 9001
  # nodePort: 9001

# volume:
  # 数据
  # data: "/var/lib/minio/data"
  # 配置
  # config: "/var/lib/minio/config"