name: alpine3.20-nginx1.26.2

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  # push:
  #   branches: [master]
  # pull_request:
  #   branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # alpineos:alpine3.20-nginx1.26.2
      - name: Build and push alpineos:alpine3.20-nginx1.26.2
        uses: docker/build-push-action@v5
        with:
          context: ./dockerfiles
          file: ./dockerfiles/Dockerfile.alpine3.20-nginx1.26.2
          push: true
          tags: shalldie/alpineos:alpine3.20-nginx1.26.2
