name: alpine3.17.2-node18.14.2-nginx1.22.1

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  # push:
  #   branches: [master]
  # pull_request:
  #   branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # alpineos:alpine3.17.2-node18.14.2-nginx1.22.1
      - name: Build and push alpineos:alpine3.17.2-node18.14.2-nginx1.22.1
        uses: docker/build-push-action@v3
        with:
          context: ./dockerfiles
          file: ./dockerfiles/Dockerfile.alpine3.17.2-node18.14.2-nginx1.22.1
          push: true
          tags: shalldie/alpineos:alpine3.17.2-node18.14.2-nginx1.22.1
